version: '3.7'
services:
  pg:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./configs/pg/graph-starter.sql:/docker-entrypoint-initdb.d/graph-starter.sql
    environment:
      - 'POSTGRES_PASSWORD=${DB_PASS}'
      - 'POSTGRES_DB=${DB_NAME}'
